const books = {
	'GEN': { eng: 'Genesis', note: '‘1 Moses’ in some Bibles' },
	'EXO': { eng: 'Exodus', note: '‘2 Moses’ in some Bibles' },
	'LEV': { eng: 'Leviticus', note: '‘3 Moses’ in some Bibles' },
	'NUM': { eng: 'Numbers', note: '‘4 Moses’ in some Bibles' },
	'DEU': { eng: 'Deuteronomy', note: '‘5 Moses’ in some Bibles' },
	'JOS': { eng: 'Joshua' },
	'JDG': { eng: 'Judges' },
	'RUT': { eng: 'Ruth' },
	'1SA': { eng: '1 Samuel', note: '1 Kings or Kingdoms in Orthodox Bibles' },
	'2SA': { eng: '2 Samuel', note: '2 Kings or Kingdoms in Orthodox Bibles' },
	'1KI': { eng: '1 Kings', note: '3 Kings or Kingdoms in Orthodox Bibles' },
	'2KI': { eng: '2 Kings', note: '4 Kings or Kingdoms in Orthodox Bibles' },
	'1CH': { eng: '1 Chronicles', note: '1 Paralipomenon in Orthodox Bibles' },
	'2CH': { eng: '2 Chronicles', note: '2 Paralipomenon in Orthodox Bibles' },
	'EZR': { eng: 'Ezra', note: 'This is for Hebrew Ezra, sometimes called 1 Ezra or 1 Esdras; also for Ezra-Nehemiah when one book' },
	'NEH': { eng: 'Nehemiah', note: 'Sometimes appended to Ezra; called 2 Esdras in the Vulgate' },
	'EST': { eng: 'Esther', note: 'This is for Hebrew Esther; for the longer Greek LXX Esther use ESG' },
	'JOB': { eng: 'Job' },
	'PSA': { eng: 'Psalms', note: '150 Psalms in Hebrew, 151 Psalms in Orthodox Bibles, 155 Psalms in West Syriac Bibles' },
	'PRO': { eng: 'Proverbs', note: '31 Proverbs, but 24 Proverbs in the Ethiopian Bible' },
	'ECC': { eng: 'Ecclesiastes', note: 'Qoholeth in Catholic Bibles; for Ecclesiasticus use SIR' },
	'SNG': { eng: 'Song of Songs', note: 'Song of Solomon, or Canticles of Canticles in Catholic Bibles' },
	'ISA': { eng: 'Isaiah', note: 'Do not confuse this abbreviation with 1SA for 1 Samuel' },
	'JER': { eng: 'Jeremiah', note: 'The Book of Jeremiah; for the Letter of Jeremiah use LJE' },
	'LAM': { eng: 'Lamentations', note: 'The Lamentations of Jeremiah' },
	'EZK': { eng: 'Ezekiel' },
	'DAN': { eng: 'Daniel', note: 'This is for Hebrew Daniel; for the longer Greek LXX Daniel use DAG' },
	'HOS': { eng: 'Hosea' },
	'JOL': { eng: 'Joel' },
	'AMO': { eng: 'Amos' },
	'OBA': { eng: 'Obadiah' },
	'JON': { eng: 'Jonah' },
	'MIC': { eng: 'Micah' },
	'NAM': { eng: 'Nahum' },
	'HAB': { eng: 'Habakkuk' },
	'ZEP': { eng: 'Zephaniah' },
	'HAG': { eng: 'Haggai' },
	'ZEC': { eng: 'Zechariah' },
	'MAL': { eng: 'Malachi' },
	'MAT': { eng: 'Matthew' },
	'MRK': { eng: 'Mark' },
	'LUK': { eng: 'Luke' },
	'JHN': { eng: 'John' },
	'ACT': { eng: 'Acts' },
	'ROM': { eng: 'Romans' },
	'1CO': { eng: '1 Corinthians' },
	'2CO': { eng: '2 Corinthians' },
	'GAL': { eng: 'Galatians' },
	'EPH': { eng: 'Ephesians' },
	'PHP': { eng: 'Philippians' },
	'COL': { eng: 'Colossians' },
	'1TH': { eng: '1 Thessalonians' },
	'2TH': { eng: '2 Thessalonians' },
	'1TI': { eng: '1 Timothy' },
	'2TI': { eng: '2 Timothy' },
	'TIT': { eng: 'Titus' },
	'PHM': { eng: 'Philemon' },
	'HEB': { eng: 'Hebrews' },
	'JAS': { eng: 'James' },
	'1PE': { eng: '1 Peter' },
	'2PE': { eng: '2 Peter' },
	'1JN': { eng: '1 John' },
	'2JN': { eng: '2 John' },
	'3JN': { eng: '3 John' },
	'JUD': { eng: 'Jude' },
	'REV': { eng: 'Revelation', note: 'Called Apocalypse in Catholic Bibles' },
	'TOB': { eng: 'Tobit' },
	'JDT': { eng: 'Judith' },
	'ESG': { eng: 'Esther Greek' },
	'WIS': { eng: 'Wisdom of Solomon' },
	'SIR': { eng: 'Sirach', note: 'Ecclesiasticus or Jesus son of Sirach' },
	'BAR': { eng: 'Baruch', note: '5 chapters in Orthodox Bibles (LJE is separate); 6 chapters in Catholic Bibles (includes LJE); called 1 Baruch in Syriac Bibles' },
	'LJE': { eng: 'Letter of Jeremiah', note: 'Sometimes included in Baruch; called ‘Rest of Jeremiah’ in Ethiopia' },
	'S3Y': { eng: 'Song of the 3 Young Men', note: 'Includes the Prayer of Azariah; sometimes included in Greek Daniel' },
	'SUS': { eng: 'Susanna', note: 'Sometimes included in Greek Daniel' },
	'BEL': { eng: 'Bel and the Dragon', note: 'Sometimes included in Greek Daniel; called ‘Rest of Daniel’ in Ethiopia' },
	'1MA': { eng: '1 Maccabees', note: 'Called ‘3 Maccabees’ in some traditions, printed in Catholic and Orthodox Bibles' },
	'2MA': { eng: '2 Maccabees', note: 'Called ‘1 Maccabees’ in some traditions, printed in Catholic and Orthodox Bibles' },
	'3MA': { eng: '3 Maccabees', note: 'Called ‘2 Maccabees’ in some traditions, printed in Orthodox Bibles' },
	'4MA': { eng: '4 Maccabees', note: 'In an appendix to the Greek Bible and in the Georgian Bible' },
	'1ES': { eng: '1 Esdras', note: 'The 9 chapter book of Greek Ezra in the LXX, called ‘2 Esdras’ in Russian Bibles, and called ‘3 Esdras’ in the Vulgate; when Ezra-Nehemiah is one book use EZR' },
	'2ES': { eng: '2 Esdras', note: 'The 16 chapter book of Latin Esdras called ‘3 Esdras’ in Russian Bibles and called ‘4 Esdras’ in the Vulgate; for the 12 chapter Apocalypse of Ezra use EZA' },
	'MAN': { eng: 'Prayer of Manasseh', note: 'Sometimes appended to 2 Chronicles, included in Orthodox Bibles' },
	'PS2': { eng: 'Psalm 151', note: 'An additional Psalm in the Septuagint, appended to Psalms in Orthodox Bibles' },
	'ODA': { eng: 'Odae/Odes', note: 'A book in some editions of the Septuagint; Odes has different contents in Greek, Russian, and Syriac traditions' },
	'PSS': { eng: 'Psalms of Solomon', note: 'A book in some editions of the Septuagint, but not printed in modern Bibles' },
	'EZA': { eng: 'Ezra Apocalypse', note: '12 chapter book of Ezra Apocalypse; called ‘3 Ezra’ in the Armenian Bible, called ‘Ezra Shealtiel’ in the Ethiopian Bible; formerly called 4ES; called ‘2 Esdras’ when it includes 5 Ezra and 6 Ezra' },
	'5EZ': { eng: '5 Ezra', note: '2 chapter Latin preface to Ezra Apocalypse; formerly called 5ES' },
	'6EZ': { eng: '6 Ezra', note: '2 chapter Latin conclusion to Ezra Apocalypse; formerly called 6ES' },
	'DAG': { eng: 'Daniel Greek', note: 'The 14 chapter version of Daniel from the Septuagint including Greek additions' },
	'PS3': { eng: 'Psalms 152-155', note: 'Additional Psalms 152-155 found in West Syriac manuscripts' },
	'2BA': { eng: '2 Baruch (Apocalypse)', note: 'The Apocalypse of Baruch in Syriac Bibles' },
	'LBA': { eng: 'Letter of Baruch', note: 'Sometimes appended to 2 Baruch; sometimes separate in Syriac Bibles' },
	'JUB': { eng: 'Jubilees', note: 'Ancient Hebrew book used in the Ethiopian Bible' },
	'ENO': { eng: 'Enoch', note: 'Sometimes called ‘1 Enoch’; ancient Hebrew book in the Ethiopian Bible' },
	'1MQ': { eng: '1 Meqabyan/Mekabis', note: 'Book of Mekabis of Benjamin in the Ethiopian Bible' },
	'2MQ': { eng: '2 Meqabyan/Mekabis', note: 'Book of Mekabis of Moab in the Ethiopian Bible' },
	'3MQ': { eng: '3 Meqabyan/Mekabis', note: 'Book of Meqabyan in the Ethiopian Bible' },
	'REP': { eng: 'Reproof', note: 'Proverbs part 2: Used in the Ethiopian Bible' },
	'4BA': { eng: '4 Baruch', note: 'Paralipomenon of Jeremiah, called ‘Rest of the Words of Baruch’ in Ethiopia; may include or exclude the Letter of Jeremiah as chapter 1, used in the Ethiopian Bible' },
	'LAO': { eng: 'Letter to the Laodiceans', note: 'A Latin Vulgate book, found in the Vulgate and some medieval Catholic translations' },
};
